name: model-production
on: [pull_request]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          # Install requirements
          pip install -r requirements.txt

          # Pull data & run-cache from GOOGLE-DRIVE and reproduce pipeline
          dvc pull creditcard.csv --run-cache
          dvc repro
          echo "## Logit Model Results" > report.md
          cat results/model_summary.txt >> report.md
          cml-send-comment report.md